// Capability statement generator.
// Template-first: fixed sections build from intake fields directly.
// Narrative section (differentiators, core competencies prose) optionally enriched via Haiku.

import {
  Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType,
  Table, TableRow, TableCell, WidthType, BorderStyle, ShadingType
} from 'docx';
import { chatHaiku } from '../llm';

const NAVY = '1B3A6B';
const GOLD = 'C9A84C';

function h(text: string, color = NAVY, size = 28) {
  return new Paragraph({
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text, bold: true, color, size, font: 'Arial' })]
  });
}

function p(text: string, size = 22) {
  return new Paragraph({
    spacing: { after: 120 },
    children: [new TextRun({ text, size, font: 'Arial' })]
  });
}

function bullet(text: string) {
  return new Paragraph({
    bullet: { level: 0 },
    spacing: { after: 60 },
    children: [new TextRun({ text, size: 22, font: 'Arial' })]
  });
}

export async function generateCapabilityStatement(intake: any): Promise<{ buffer: Buffer; filename: string }> {
  const name = intake.company_name || intake.name || 'Company';
  const naics = (intake.naics_codes || '').toString();
  const poc = intake.primary_poc_name || '';
  const email = intake.primary_poc_email || '';
  const phone = intake.primary_poc_phone || '';
  const summary = intake.capabilities_summary || '';
  const past = intake.past_performance || '';
  const diffs = intake.differentiators || '';
  const agencies = intake.target_agencies || 'All federal agencies';
  const state = intake.state || '';
  const ein = intake.ein || '';
  const uei = intake.uei || '';
  const cage = intake.cage_code || '';

  // Optionally enrich the differentiators paragraph with Haiku if it's thin
  let enrichedDiffs = diffs;
  try {
    if (diffs && diffs.length < 120) {
      const out = await chatHaiku(
        'You expand terse SDVOSB capability statement bullets into polished federal-grade prose. Keep it factual. No fluff. Two sentences max.',
        `Company: ${name}\nCore: ${summary}\nRaw differentiators: ${diffs}\nExpand the differentiators into two crisp sentences.`
      );
      enrichedDiffs = out.text.trim();
    }
  } catch { /* budget exceeded or relay down — keep raw */ }

  const doc = new Document({
    creator: 'SWTMT Portal',
    title: `${name} Capability Statement`,
    styles: {
      default: { document: { run: { font: 'Arial' } } }
    },
    sections: [{
      properties: { page: { margin: { top: 720, bottom: 720, left: 720, right: 720 } } },
      children: [
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [new TextRun({ text: name.toUpperCase(), bold: true, size: 40, color: NAVY, font: 'Arial' })]
        }),
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 200 },
          children: [new TextRun({ text: 'Capability Statement', italics: true, size: 26, color: GOLD, font: 'Arial' })]
        }),

        h('Company Overview'),
        p(summary || `${name} is a Service-Disabled Veteran-Owned Small Business providing federal contracting solutions.`),

        h('Core Competencies'),
        ...(summary ? summary.split('.').filter((s: string) => s.trim().length > 5).map((s: string) => bullet(s.trim())) : [bullet('Add core competencies via intake')]),

        h('Differentiators'),
        p(enrichedDiffs || 'SDVOSB-certified. Veteran-led. Responsive delivery.'),

        h('Past Performance'),
        p(past || 'Past performance details available upon request.'),

        h('Corporate Data'),
        bullet(`Legal Name: ${name}`),
        bullet(`State of Formation: ${state}`),
        bullet(`EIN: ${ein || 'On file'}`),
        bullet(`UEI: ${uei || 'On file'}`),
        bullet(`CAGE Code: ${cage || 'Pending'}`),
        bullet(`NAICS Codes: ${naics || 'See capabilities'}`),
        bullet(`SDVOSB Certified: ${intake.sdvosb_certified ? 'Yes' : 'In progress'}`),
        bullet(`Target Agencies: ${agencies}`),

        h('Point of Contact'),
        p(`${poc}`),
        p(`${email}`),
        p(`${phone}`),

        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 400 },
          children: [new TextRun({ text: 'Generated by SWTMT Portal', italics: true, size: 18, color: '888888', font: 'Arial' })]
        })
      ]
    }]
  });

  const buffer = await Packer.toBuffer(doc);
  const safeName = name.replace(/[^a-z0-9]+/gi, '_');
  return { buffer, filename: `${safeName}_Capability_Statement.docx` };
}
